### ISSUE TITLE
How do you generate your icons?

### ISSUE THREAD

**Issue by tabuchid** [vincentchan/mickey#4]
I notice you have to replace logo-text-black.svg for the header text. Is there a tool you use for generating that?

**Comment by vincentchan** [comment]
The reason I used logo-text-black.svg, created by adobe illustrator, is because I want to use a particular font (Gotham) for the logo image. If you want to change the logo, feel free to change the classes `.textLogo` for image source and `.textLogo--frontpage` for image size.

If you want to use a pure text logo, feel free to remove `text-indent: -100em;` and `background-image: url(../images/logo-text-black.svg);` from `.textLogo` and remove the class `.textLogo--frontpage`

https://github.com/vincentchan/mickey/blob/master/_scss/_global.scss

**Comment by tabuchid** [comment]
Great. Thank you! and I really like this design too.
I'm am noticing another tricky thing based on baseurl but will open another task for that.

**Comment by vincentchan** [comment]
Glad you like it! If you have any difficulties when setting up the theme, just let me know here. Happy to help.
